<?php
/**
 * @file
 * EU cookie compliance redirect primary module file.
 *
 * This module will provide the possibility to accept or deny the cookies from a separate page.
 *
 * Author: Frederik Van Hooghten
 */

/**
 * Implements hook_menu().
 */
function eu_cookie_compliance_redirect_menu() {

  $items = [];

  $items['cookie/delete'] = [
    'title' => t('Delete popup'),
    'page callback' => 'eu_cookie_compliance_redirect_deny',
    'access callback' => TRUE,
    'menu_name' => ''
  ];

  $items['cookie/accept'] = [
    'title' => t('Accept popup'),
    'page callback' => 'eu_cookie_compliance_redirect_accept',
    'access callback' => TRUE,
    'menu_name' => ''
  ];

  return $items;
}

/**
 * Callback that sets the cookie-agreed value to 'not accepted'.
 *
 * @return mixed
 *   Returns fallback text to notify the visitor.
 */
function eu_cookie_compliance_redirect_deny() {
  setcookie('cookie-agreed', 0, time() + (86400 * 365), '/');
  drupal_add_js(drupal_get_path('module', 'eu_cookie_compliance_redirect') . '/redirect.js');
  return t('Your choice has been saved.');
}

/**
 * Callback that sets the cookie-agreed value to 'accepted'.
 *
 * @return mixed
 *   Returns fallback text to notify the visitor.
 */
function eu_cookie_compliance_redirect_accept() {
  setcookie('cookie-agreed', 2, time() + (86400 * 365), '/');
  drupal_add_js(drupal_get_path('module', 'eu_cookie_compliance_redirect') . '/redirect.js');
  return t('Your choice has been saved.');
}

/**
 * Implements hook_preprocess_page().
 *
 * Add jQuery Cookie library to the entire site.
 */
function eu_cookie_compliance_redirect_preprocess_page(&$vars) {
  drupal_add_library('system', 'jquery.cookie');
}